// <auto-generated />
using System;
using GoChauffeurWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoChauffeurWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240625125248_jbckdsd")]
    partial class jbckdsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoChauffeurWebApi.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.AdvanceAmount", b =>
                {
                    b.Property<int>("AdvanceAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvanceAmountId"));

                    b.Property<decimal?>("Advance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TripTypeId")
                        .HasColumnType("int");

                    b.HasKey("AdvanceAmountId");

                    b.ToTable("AdvanceAmounts");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.AerialDistancePrice", b =>
                {
                    b.Property<int>("AerialDistancePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AerialDistancePriceId"));

                    b.Property<string>("AerialDistancePriceperKilometer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AerialDistancePriceId");

                    b.ToTable("AerialDistancePrices");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Anonymoustripcharges", b =>
                {
                    b.Property<int>("AnonymoustripchargesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnonymoustripchargesId"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("TriptypeId")
                        .HasColumnType("int");

                    b.HasKey("AnonymoustripchargesId");

                    b.ToTable("Anonymoustripcharges");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Cupons", b =>
                {
                    b.Property<int>("CuponsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuponsId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int");

                    b.Property<string>("CuponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuponName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Flag")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuponsId");

                    b.ToTable("Cupons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.CuponsHistory", b =>
                {
                    b.Property<int>("CuponsHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuponsHistoryId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CuponsHistoryId");

                    b.ToTable("CuponsHistories");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.CustomerTicketReasons", b =>
                {
                    b.Property<int>("CustomerTicketReasonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerTicketReasonsId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerTicketReasonsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerTicketReasonsId");

                    b.ToTable("CustomerTicketReasons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.CustomerTickets", b =>
                {
                    b.Property<int>("CustomerTicketsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerTicketsId"));

                    b.Property<bool?>("IsTicketClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Reasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerTicketsId");

                    b.ToTable("CustomerTickets");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.CustomerWallet", b =>
                {
                    b.Property<int>("CustomerWalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerWalletId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WalletBalance")
                        .HasColumnType("int");

                    b.HasKey("CustomerWalletId");

                    b.ToTable("CustomerWallets");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.CustomerWalletFine", b =>
                {
                    b.Property<int>("CustomerWalletFineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerWalletFineId"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("FineName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerWalletFineId");

                    b.ToTable("CustomerWalletFines");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("AadharNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharNumberBackImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharNumberFrontImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverRecID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Experiance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDriverActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPaymentDone")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenceBackImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenceFrontImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licencevalidddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfTripsCount")
                        .HasColumnType("int");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PANNumberBackImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PANNumberFrontImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermenentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermenentCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermenentCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermenentPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermenentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferedBy")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscribedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TodaysEarning")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TodaysLogInHrs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransmissionTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTypeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatusIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("reasonforoffline")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverFines", b =>
                {
                    b.Property<int>("DriverFinesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverFinesId"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("DriverFinesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverFinesId");

                    b.ToTable("DriverFines");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverPenalty", b =>
                {
                    b.Property<int>("DriverPenaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverPenaltyId"));

                    b.Property<string>("Balance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverPenaltyId");

                    b.ToTable("DriverPenalties");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverTickets", b =>
                {
                    b.Property<int>("DriverTicketsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverTicketsId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsTicketClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Reasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("DriverTicketsId");

                    b.ToTable("DriverTickets");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverTicketsReason", b =>
                {
                    b.Property<int>("DriverTicketsReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverTicketsReasonId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverTicketsReasonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("DriverTicketsReasonId");

                    b.ToTable("DriverTicketsReasons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverTracking", b =>
                {
                    b.Property<int>("DriverTrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverTrackingId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("DriverTrackingId");

                    b.ToTable("DriverTrackings");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverTransaction", b =>
                {
                    b.Property<int>("DriverTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverTransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsJoiningFee")
                        .HasColumnType("bit");

                    b.Property<string>("transactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverTransactionId");

                    b.ToTable("DriverTransactions");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverWalletDeductionResons", b =>
                {
                    b.Property<int>("DriverWalletDeductionResonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverWalletDeductionResonsId"));

                    b.Property<string>("DriverWalletDeductionResonsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverWalletDeductionResonsId");

                    b.ToTable("DriverWalletDeductionResons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.DriverWalletTransactionHistory", b =>
                {
                    b.Property<int>("DriverWalletTransactionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverWalletTransactionHistoryId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WalletAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DriverWalletTransactionHistoryId");

                    b.ToTable("DriverWalletTransactionHistories");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Driver_Joining_Fee", b =>
                {
                    b.Property<int>("Driver_Joining_FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Driver_Joining_FeeId"));

                    b.Property<string>("Fee")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Driver_Joining_FeeId");

                    b.ToTable("Driver_Joining_Fees");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Driversubscription", b =>
                {
                    b.Property<int>("DriversubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriversubscriptionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Expirydate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("transactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriversubscriptionId");

                    b.ToTable("Driversubscriptions");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Driversurroundingtrips", b =>
                {
                    b.Property<int>("DriversurroundingtripsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriversurroundingtripsId"));

                    b.Property<int?>("Distance")
                        .HasColumnType("int");

                    b.HasKey("DriversurroundingtripsId");

                    b.ToTable("Driversurroundingtrips");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Driverwallet", b =>
                {
                    b.Property<int>("DriverwalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverwalletId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverWalletDeductionResonsId")
                        .HasColumnType("int");

                    b.Property<string>("WalletBalance")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverwalletId");

                    b.ToTable("Driverwallets");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Favourite", b =>
                {
                    b.Property<int>("FavouriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavouriteId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavouriteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FavouriteTypesId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("mapUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavouriteId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.FavouriteTypes", b =>
                {
                    b.Property<int>("FavouriteTypesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavouriteTypesId"));

                    b.Property<string>("FavouriteTypesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavouriteTypesId");

                    b.ToTable("FavouriteTypes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Flexi", b =>
                {
                    b.Property<int>("FlexiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlexiId"));

                    b.Property<decimal?>("AdvancePaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("CloseTrip")
                        .HasColumnType("bit");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DriverMeansOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedCuponPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EstimatedTaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FlexiSelectedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdvancePaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDriverAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTripCompByDriver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTripStarted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsdriverArrived")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoofDays")
                        .HasColumnType("int");

                    b.Property<string>("PickUPMapURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickUpTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransmissionId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueflexiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersTripsCancelResonsId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("FlexiId");

                    b.ToTable("Flexis");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.FlexiDatesList", b =>
                {
                    b.Property<int>("FlexiDatesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlexiDatesListId"));

                    b.Property<decimal?>("ActualCuponPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActualHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ActualTaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverMeansOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriversPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlexiId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrlsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDriverArrival")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTripCompByDriver")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTripStarted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("endtime")
                        .HasColumnType("datetime2");

                    b.HasKey("FlexiDatesListId");

                    b.ToTable("FlexiDatesLists");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Hours", b =>
                {
                    b.Property<int>("HoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoursId"));

                    b.Property<int?>("Charges")
                        .HasColumnType("int");

                    b.Property<int?>("HoursName")
                        .HasColumnType("int");

                    b.Property<bool?>("IsinHours")
                        .HasColumnType("bit");

                    b.Property<int?>("NightCharges")
                        .HasColumnType("int");

                    b.Property<int>("TripTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TripVarientId")
                        .HasColumnType("int");

                    b.HasKey("HoursId");

                    b.ToTable("Hours");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.IgnoreFlexiTrips", b =>
                {
                    b.Property<int>("IgnoreFlexiTripsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgnoreFlexiTripsId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("FlexiId")
                        .HasColumnType("int");

                    b.Property<int?>("IgnoretripresonsId")
                        .HasColumnType("int");

                    b.HasKey("IgnoreFlexiTripsId");

                    b.ToTable("IgnoreFlexiTrips");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.IgnoreMontlyTrips", b =>
                {
                    b.Property<int>("IgnoreMontlyTripsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgnoreMontlyTripsId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("IgnoretripresonsId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyId")
                        .HasColumnType("int");

                    b.HasKey("IgnoreMontlyTripsId");

                    b.ToTable("IgnoreMontlyTrips");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.IgnoreValletTrips", b =>
                {
                    b.Property<int>("IgnoreValletTripsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgnoreValletTripsId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("IgnoretripresonsId")
                        .HasColumnType("int");

                    b.Property<int>("ValetParkingId")
                        .HasColumnType("int");

                    b.HasKey("IgnoreValletTripsId");

                    b.ToTable("IgnoreValletTrips");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.IgnoredTrips", b =>
                {
                    b.Property<int>("IgnoredTripsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgnoredTripsID"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("IgnoredTripsID");

                    b.ToTable("IgnoredTrips");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Ignoretripresons", b =>
                {
                    b.Property<int>("IgnoretripresonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgnoretripresonsId"));

                    b.Property<string>("IgnoretripresonsDescrption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IgnoretripresonsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IgnoretripresonsId");

                    b.ToTable("ignoretripresons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.InsurenceTaxandPrice", b =>
                {
                    b.Property<int>("InsurenceTaxandPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsurenceTaxandPriceId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InsurenceTaxandPriceId");

                    b.ToTable("InsurenceTaxandPrice");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Monthly", b =>
                {
                    b.Property<int>("MonthlyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlyId"));

                    b.Property<bool?>("CloseTrip")
                        .HasColumnType("bit");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DriverMeansOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("Estimatedprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdvancedPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPermanent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTripCompByDriver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTripStarted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsdriverArrived")
                        .HasColumnType("bit");

                    b.Property<int?>("NoofDays")
                        .HasColumnType("int");

                    b.Property<string>("PickUpLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickUpLocationCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupMapURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Pickuptime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SelectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransmissionId")
                        .HasColumnType("int");

                    b.Property<int?>("TripVarientId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueMonthlyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersTripsCancelResonsId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("MonthlyId");

                    b.ToTable("Monthlies");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.MonthlyDateList", b =>
                {
                    b.Property<int>("MonthlyDateListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlyDateListId"));

                    b.Property<decimal?>("ActualCuponPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActualHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ActualTaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverMeansOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriversPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrlsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDriverArrival")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTripCompByDriver")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTripStarted")
                        .HasColumnType("bit");

                    b.Property<int?>("MonthlyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("endtime")
                        .HasColumnType("datetime2");

                    b.HasKey("MonthlyDateListId");

                    b.ToTable("MonthlyDateLists");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.NightCharges", b =>
                {
                    b.Property<int>("NightChargesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NightChargesId"));

                    b.Property<decimal?>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("NightChargesId");

                    b.ToTable("NightCharges");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.OutstationRoundtriphours", b =>
                {
                    b.Property<int>("HoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoursId"));

                    b.Property<int?>("Charges")
                        .HasColumnType("int");

                    b.Property<int?>("HoursName")
                        .HasColumnType("int");

                    b.Property<bool?>("IsinHours")
                        .HasColumnType("bit");

                    b.Property<int>("TripTypeId")
                        .HasColumnType("int");

                    b.HasKey("HoursId");

                    b.ToTable("OutstationRoundtriphours");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("PaymentStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentStatusId");

                    b.ToTable("PaymentStatus");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("PaymentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Ratings", b =>
                {
                    b.Property<int>("RatingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingsId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("RatingsId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Refer", b =>
                {
                    b.Property<int>("ReferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferId"));

                    b.Property<bool?>("Isused")
                        .HasColumnType("bit");

                    b.Property<string>("ReferalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReferId");

                    b.ToTable("Referals");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.RequiredValetstaffs", b =>
                {
                    b.Property<int>("RequiredValetstaffsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequiredValetstaffsId"));

                    b.Property<int?>("NumberOfDrivers")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfSupervisors")
                        .HasColumnType("int");

                    b.HasKey("RequiredValetstaffsId");

                    b.ToTable("RequiredValetstaffs");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesId"));

                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolesId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Schuduletriptimechagemodel", b =>
                {
                    b.Property<int>("SchuduletriptimechagemodelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchuduletriptimechagemodelId"));

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchuduletripDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripTypeId")
                        .HasColumnType("int");

                    b.HasKey("SchuduletriptimechagemodelId");

                    b.ToTable("Schuduletriptimechagemodel");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.ServicePlaces", b =>
                {
                    b.Property<int>("ServicePlacesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicePlacesId"));

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServicePlacesId");

                    b.ToTable("ServicePlaces");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<decimal?>("AfterGsttotalsubamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsDriverSub")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubscripationGstId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.SubscriptionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("SubEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionHistories");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Tax", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxId"));

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaxId");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.TransmissionType", b =>
                {
                    b.Property<int>("TransmissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransmissionTypeId"));

                    b.Property<string>("TransmissionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransmissionTypeId");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AerialDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BookedForName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookedForNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistanceTravelled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DriverMeansOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverRating")
                        .HasColumnType("int");

                    b.Property<string>("DriversPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropUPMapURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstimatedPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExpectedDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FromLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromLocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrlsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSecuredTrip")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSelfBook")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTimeScheduled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTripCompByDriver")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTripStarted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsdriverArrived")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOfHoursActual")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfHoursSelected")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PickUPMapURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequstedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaxIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToLocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalTripValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransmissionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TripRating")
                        .HasColumnType("int");

                    b.Property<int?>("TripStatus")
                        .HasColumnType("int");

                    b.Property<int?>("TripTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TripsUniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TripvarientId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersTripsCancelResonsId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.TripCancellationReasons", b =>
                {
                    b.Property<int>("TripCancellationReasonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripCancellationReasonsId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TripCancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripCancellationReasonsId");

                    b.ToTable("TripCancellationReasons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.TripStatus", b =>
                {
                    b.Property<int>("TripStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripStatusId"));

                    b.Property<string>("TripStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripStatusId");

                    b.ToTable("TripStatuses");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.TripTax", b =>
                {
                    b.Property<int>("TripTaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripTaxId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TripTaxId");

                    b.ToTable("TripTaxes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.TripType", b =>
                {
                    b.Property<int>("TripTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripTypeId"));

                    b.Property<string>("Endtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Starttime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripTypeId");

                    b.ToTable("TripTypes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.TripVariant", b =>
                {
                    b.Property<int>("TripVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripVariantId"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChargesperMinute")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsTripOneway")
                        .HasColumnType("bit");

                    b.Property<decimal?>("KilometerLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NightCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PricePerKilometers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TripVariantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TriptypeId")
                        .HasColumnType("int");

                    b.HasKey("TripVariantId");

                    b.ToTable("TripVariants");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.UsersTripsCancelResons", b =>
                {
                    b.Property<int>("UsersTripsCancelResonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsersTripsCancelResonsId"));

                    b.Property<string>("UserTripsCancelResonsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsersTripsCancelResonsId");

                    b.ToTable("UsersTripsCancelResons");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.ValetParking", b =>
                {
                    b.Property<int>("ValetParkingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValetParkingId"));

                    b.Property<decimal?>("AdvanceAMount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DriverMeansOfTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GSTPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GSTPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdvancePaid")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfDriversRequired")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfHours")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfSupervisors")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniquevaletParkingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValetParkingId");

                    b.ToTable("ValetParkings");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.ValetParkingHourlyPrices", b =>
                {
                    b.Property<int>("ValetParkingHourlyPricesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValetParkingHourlyPricesId"));

                    b.Property<int?>("DriverPrice")
                        .HasColumnType("int");

                    b.Property<int?>("SuperVisorPrice")
                        .HasColumnType("int");

                    b.HasKey("ValetParkingHourlyPricesId");

                    b.ToTable("ValetParkingHourlyPrices");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.ValetParkingPricing", b =>
                {
                    b.Property<int>("ValetParkingPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValetParkingPricingId"));

                    b.Property<decimal?>("BaseHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DriverCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HourlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupervisorCharges")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ValetParkingPricingId");

                    b.ToTable("ValetParkingPricing");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.ValetparkingStaff", b =>
                {
                    b.Property<int>("ValetparkingStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValetparkingStaffId"));

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Isregistrationclosed")
                        .HasColumnType("bit");

                    b.Property<string>("SuperVisiorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValetParkingId")
                        .HasColumnType("int");

                    b.HasKey("ValetparkingStaffId");

                    b.ToTable("ValetparkingStaff");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("GoChauffeurWebApi.Models.VerificationStatus", b =>
                {
                    b.Property<int>("VerificationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationStatusId"));

                    b.Property<string>("VerificationStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerificationStatusId");

                    b.ToTable("VerificationStatuses");
                });

            modelBuilder.Entity("GoChauffeurWebApi.SubscripationGst", b =>
                {
                    b.Property<int>("SubscripationGstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscripationGstId"));

                    b.Property<string>("GstPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscripationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscripationGstId");

                    b.ToTable("SubscripationGst");
                });
#pragma warning restore 612, 618
        }
    }
}
